### ISSUE TITLE
Make app not reliant on export

### ISSUE THREAD

**Issue by michaelachrisco** [westernmilling/gman_client#6]
Add Figaro gem or initialize gem with:

* CLIENT_ID
* CLIENT_SECRET
* URL
* TOKEN_URL

**Comment by josephbridgwaterrowe** [comment]
Is this the issue to create an initialize method that accepts the connection parameters?

Also the client would be used as an instance rather than a static class?

**Comment by michaelachrisco** [comment]
At the moment, the module is using the environment but can be overridden via:
```
2.1.4 :003 > GmanClient.token_url
 => "http://localhost:3000/oauth/token" 
2.1.4 :004 > GmanClient.token_url='hello'
 => "hello" 
2.1.4 :005 > GmanClient.token_url
 => "hello" 
```
The idea is to use Figaro but using the parent application. At the moment, the gem works and the parent could use Figaro to rewrite the parameters for the module.

**Comment by josephbridgwaterrowe** [comment]
I would recommend the rewrite to use an initializer to create a new instance of the client with the connection details provided. Of course figaro or env could be used in the calling code to populate said parameters.
